if: branch = master OR type = pull_request
language: python
python: ['3.6']
env:
  - AWS_DEFAULT_REGION=us-east-1
services:
  - docker
install:
  - sudo apt-get install python3-pip
  - pip install awscli
  - pip install aws-sam-cli
  - rvm install ruby-2.5.3
  - ruby --version
before_script:
  - ./bin/setup
script:
  - ./bin/test
