AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Using Ruby with AWS Lambda & SAM by 757rb.org

Parameters:

  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - staging
      - prod

Resources:

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: ruby2.5
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          STAGE: !Ref StageName
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !GetAtt PlosSearchTable.Arn
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /{resource+}
            Method: get

  PlosSearchTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Join
        - ''
        - - plos-search
          - '-'
          - !Ref StageName
      PrimaryKey:
        Name: id
        Type: String

Outputs:

  MyApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  Function:
    Description: Lambda function ARN.
    Value: !GetAtt MyFunction.Arn

  FunctionIamRole:
    Description: Implicit IAM Role created for the function.
    Value: !GetAtt MyFunctionRole.Arn
